# Generated by Django 5.1.6 on 2025-03-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='calf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Łydka'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='chest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Klatka piersiowa'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='forearm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Przedramię'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='hips',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Biodra'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='thigh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Udo'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='waist',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Talia'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Waga'),
        ),
    ]
